---
# tasks file for tower-setup
#- name: Role run ping host
#  include: ping.yml

#- name: Role download tower
#  include: get-tower.yml

#- name: Role run set-ram
#  include: set-ram.yml

#- name: Role run set password
#  include: set-password.yml

- name: Installing tower now
#  become: true
  include: install.yml