- name: Get path
  shell: ls /tmp/ansible-tower
  register: r0

- name:
  debug:
    msg: "{{r0.stdout_lines[0]}}"
  register: r1

- name: Set pssword to tower dasboard
  lineinfile:
    path: /tmp/ansible-tower/{{r1.msg}}/inventory
    regexp: '^admin_password'
    line: "admin_password={{admin_password}}"

- name: Set password on tower database
  lineinfile:
    path: /tmp/ansible-tower/{{r1.msg}}/inventory
    regexp: '^pg_password'
    line: "pg_password={{admin_password}}"
