- name: Set pssword to tower dasboard
  lineinfile:
    path: ansible-tower-setup-3.8.3-2/inventory
    regexp: ^admin_password
    line: "admin_password={{admin_password}}"

- name: Set password on tower database
  lineinfile:
    path: ansible-tower-setup-3.8.3-2/inventory
    regexp: ^pg_password
    line: "pg_password={{admin_password}}"
