---
- name: Validating kube config
  include: validate-kubeconfig.yaml

- name: Generate rsa key and csr
  include: generate-crt.yaml

- name: Validate csr
  include: generate-rbac.yaml

- name: Create kubeconfig file
  include: generate-config.yaml