- name: Creating temporary dir at /tmp/k8s-rbac
  file:
    path: /tmp/k8s-rbac
    state: directory
    mode: "0777"

- name: Copying provde kubeconfig file to /tmp/k8s-rbac
  copy:
    src: config
    dest: /tmp/k8s-rbac

- name: Validating provided kubeconfig file.
  shell: kubectl get no --kubeconfig=/tmp/k8s-rbac/config
  register: r0
  ignore_errors: yes

- debug:
    msg: "{{r0.stdout_lines}}"

- fail:
    msg: "kubeconfig file is invalid"
  when: r0.rc != 0
